CREATE TABLE [dv].[SatSecurities]
(	
	[HKeySecurity]					BINARY(20) NOT NULL,	
	[Meta_LoadDateTime]				DATETIME2 NOT NULL,
	[Meta_LoadEndDateTime]			DATETIME2 NOT NULL DEFAULT N'9999-12-31',
	[Meta_RecordSource]				NVARCHAR (1000) NOT NULL,
	[Meta_ETLProcessID]				INT	NOT NULL,				-- FK to ID of import batch 		
	[HDiffSecurityPL]				BINARY(20) NOT NULL,     	

	[SecID]					NVARCHAR(100) NULL,
	[IssuerName]			NVARCHAR(100) NULL,
	[IssueDesc]				NVARCHAR(100) NULL,
	[Ticker]				NVARCHAR(100) NULL,
	[PrimaryType]			NVARCHAR(100) NULL,
	[SecondaryType]			NVARCHAR(100) NULL,
	[TertiaryType]			NVARCHAR(100) NULL,
	[IsFloatingRate]		NVARCHAR(100) NULL,
	[IsFwdBwdSecID]			NVARCHAR(100) NULL,
	[IncomePayFreq]			NVARCHAR(100) NULL,
	[IncomeStatus]			NVARCHAR(100) NULL,
	[PriceCcy]				NVARCHAR(100) NULL,
	[IncomeCcy]				NVARCHAR(100) NULL,
	[EarningsCcy]			NVARCHAR(100) NULL,
	[PriceCcyISO]			NVARCHAR(100) NULL,
	[IncomeCcyISO]			NVARCHAR(100) NULL,
	[EarningsCcyISO]		NVARCHAR(100) NULL,
	[ResidenceCtry]			NVARCHAR(100) NULL,
	[AnnualIncome]			NUMERIC(38,20) NULL,
	[CurrentExDate]			DATETIME2 NULL,
	[LastAdjDate]			DATETIME2 NULL,
	[SplitRate]				NUMERIC(38,20) NULL,
	[FirstInterestDate]		DATETIME2 NULL,
	[Latest12MthEPS]		NUMERIC(38,20) NULL,
	[FxDealRate]			NUMERIC(38,20) NULL,
	[AccrualDate]			DATETIME2 NULL,
	[PaymentStream]			NVARCHAR(100) NULL,
	[FRSUSchCode]			NVARCHAR(100) NULL,
	[VotingCode]			NVARCHAR(100) NULL,
	[SettleDTCEligible]		NVARCHAR(100) NULL,
	[StdIndustryClass]		NVARCHAR(100) NULL,
	[IssueDate]				DATETIME2 NULL,
	[RedeemDate]			DATETIME2 NULL,
	[AltRedeemDate]			DATETIME2 NULL,
	[ConstPrepayRate]		NUMERIC(38,20) NULL,
	[OutstandingShares]		NUMERIC(38,20) NULL,
	[BondIssuerType]		NVARCHAR(100) NULL,
	[NextCallDate]			DATETIME2 NULL,
	[Multiplier]			NUMERIC(38,20) NULL,
	[NextCallPrice]			NUMERIC(38,20) NULL,
	[SecCategory]			NVARCHAR(100) NULL,
	[IssuerCode]			NVARCHAR(100) NULL,
	[CompoundingFreq]		NVARCHAR(100) NULL,
	[LastUpdate]			DATETIME2 NULL,
	[EntryDate]				DATETIME2 NULL,
	[DbSource]				NVARCHAR(100) NULL,
	[ExchangeCtry]			NVARCHAR(100) NULL,

	CONSTRAINT [PK_SatSecurities] PRIMARY KEY NONCLUSTERED ([HKeySecurity], [Meta_LoadDateTime])
)
