CREATE TABLE [dv].[SatTransactions]
(
	[HKeyTransaction]				BINARY(20) NOT NULL,	
	[Meta_LoadDateTime]				DATETIME2 NOT NULL,	
	[Meta_LoadEndDateTime]			DATETIME2 NOT NULL DEFAULT N'9999-12-31',
	[SeqEntryDateTime]				BIGINT NOT NULL,				-- Sequence No representing date\time down to millisecond - PK 
	[Meta_RecordSource]				NVARCHAR (1000) NOT NULL,
	[Meta_ETLProcessID]				INT	NOT NULL,				-- FK to ID of import batch 		
	[HDiffTransactionPL]			BINARY(20) NOT NULL, 

	[TRANNUM_Original]				NVARCHAR (100) NULL,
	[PORTCODE]						NVARCHAR (100) NULL,
	[SECID]							NVARCHAR (100) NULL,
	[TRANTYPE]						NVARCHAR (100) NULL,
	[FOOTNOTE]						NVARCHAR (100) NULL,
	[CLASS]							NVARCHAR (100) NULL,
	[TRADDATE]						DATETIME2 NULL,
	[SETTDATE]						DATETIME2 NULL,
	[BROKCODE]						NVARCHAR (100) NULL,	
	[SHAREPAR]						NUMERIC(38,20) NULL,
	
	[PriceCcyISO]					NVARCHAR (100) NULL,				-- Move to BV?
	[SettleCcyISO]					NVARCHAR (100) NULL,				-- Move to BV?

	[FXRATE]						NUMERIC(38,20) NULL,
	[FXRATEPS]						NUMERIC(38,20) NULL,
	[FXRATESB]						NUMERIC(38,20) NULL,
	[PRICEU]						NUMERIC(38,20) NULL,

	[PRICCURR]						NVARCHAR(100) NULL,
	[SETTCURR]						NVARCHAR(100) NULL,
	
	[GROSAMTU]						NUMERIC(38,20) NULL,
	[COMMISSU]						NUMERIC(38,20) NULL,
	[MISCTOTU]						NUMERIC(38,20) NULL,
	[NETAMTU]						NUMERIC(38,20) NULL,
	[COSTOTLU]						NUMERIC(38,20) NULL,
	[GAINU]							NUMERIC(38,20) NULL,
	[GROSAMTC]						NUMERIC(38,20) NULL,
	[COMMISSC]						NUMERIC(38,20) NULL,
	[MISCTOTC]						NUMERIC(38,20) NULL,
	[NETAMTC]						NUMERIC(38,20) NULL,
	[COSTOTLC]						NUMERIC(38,20) NULL,
	[GAINC]							NUMERIC(38,20) NULL,

	[QuantityChange]				NUMERIC(38,20) NULL,		-- Move to BV?
	[CostChangeLC]					NUMERIC(38,20) NULL,		-- Move to BV?
	[CostChangeBC]					NUMERIC(38,20) NULL,		-- Move to BV?
	
	[DEBITU]						NUMERIC(38,20) NULL,
	[CREDITU]						NUMERIC(38,20) NULL,
	[DEBITS]						NUMERIC(38,20) NULL,
	[CREDITS]						NUMERIC(38,20) NULL,
	[DEBITC]						NUMERIC(38,20) NULL,
	[CREDITC]						NUMERIC(38,20) NULL,
			
	[NetCashLC]						NUMERIC(38,20) NULL,		-- Move to BV?
	[NetCashSC]						NUMERIC(38,20) NULL,		-- Move to BV?
	[NetCashBC]						NUMERIC(38,20) NULL,		-- Move to BV?

	[TRADTYPE]						NVARCHAR (100) NULL,
	[ANNOT]							NVARCHAR (100) NULL,
	[EXCUM]							NVARCHAR (100) NULL,
	[EXREFNUM]						INT NULL,
	
	[MISC1U]						NUMERIC(38,20) NULL,
	[MISC2U]						NUMERIC(38,20) NULL,
	[MISC3U]						NUMERIC(38,20) NULL,
	[MISC4U]						NUMERIC(38,20) NULL,
	[MISC5U]						NUMERIC(38,20) NULL,
	[MISC6U]						NUMERIC(38,20) NULL,

	[MISC1C]						NUMERIC(38,20) NULL,
	[MISC2C]						NUMERIC(38,20) NULL,
	[MISC3C]						NUMERIC(38,20) NULL,
	[MISC4C]						NUMERIC(38,20) NULL,
	[MISC5C]						NUMERIC(38,20) NULL,
	[MISC6C]						NUMERIC(38,20) NULL,
	[MISCCODS]						NVARCHAR (100) NULL,

	[STATUS]						NVARCHAR (100) NULL,
	[ENTRDATE]						DATETIME2 NULL,
	[ENTRTIME]						TIME(7)	NULL,
	[ENTRDATETIME]					DATETIME2 NULL,
	[EFFEDATE]						DATETIME2 NULL,
	[MODIDATE]						DATETIME2 NULL,
	[MODITIME]						TIME(7)	NULL,
	[MODIDATETIME]					DATETIME2 NULL,
	   
    CONSTRAINT [PK_SatTransactions]		PRIMARY KEY NONCLUSTERED ( [HKeyTransaction], [Meta_LoadDateTime], [SeqEntryDateTime] )
)
