CREATE TABLE [stg].[HSBCNET_CustodianPositions]
(
	[ID]										INT IDENTITY(1,1) NOT NULL PRIMARY KEY,

	[In_SecuritiesAccountNumber]				VARCHAR (100) NULL,
	[In_AccountName]							VARCHAR (100) NULL,
	[In_IssueType]								VARCHAR (100) NULL,
	[In_ISIN]									VARCHAR (100) NULL,
	[In_SecurityDescription]					VARCHAR (100) NULL,
	[In_AssetLocation]							VARCHAR (100) NULL,
	[In_LocationDescription]					VARCHAR(100) NULL,
	[In_IssueTypeDescription]					VARCHAR(100) NULL,
	[In_LocationCode]							VARCHAR(100) NULL,
	[In_RegistrarCode]							VARCHAR(100) NULL,
	[In_MaturityDate]							VARCHAR(100) NULL,
	[In_TradedAggregate]						VARCHAR (100) NULL,
	[In_RegistrationCode]						VARCHAR(100) NULL,
	[In_RegistrarDescription]					VARCHAR(100) NULL,
	[In_SettledAggregate]						VARCHAR (100) NULL,
	[In_SecurityOnLoan]							VARCHAR(100) NULL,
	[In_RegistrationDescription]				VARCHAR(100) NULL,	
	[In_AvailableBalance]						VARCHAR (100) NULL,
	[In_SEDOL]									VARCHAR (100) NULL,		
	[In_SecurityPrice]							VARCHAR (100) NULL,
	[In_SecurityCurrency]						VARCHAR (100) NULL,
	[In_TradedValue_SecurityCurrency]			VARCHAR (100) NULL,
	[In_SettledAggregateValue_SecurityCurrency]	VARCHAR (100) NULL,
	[In_AccountCurrency]						VARCHAR (100) NULL,
	[In_TradedValue_AccountCurrency]			VARCHAR (100) NULL,
	[In_SettledAggregateValue_AccountCurrency]	VARCHAR (100) NULL,
	[In_ExchangeRate]							VARCHAR (100) NULL,
	
	[Out_ReportDate]								DATE NULL,				--	UIX				
	[Out_AsOfDateTime]								DATETIME2 NULL,

	[Out_SecuritiesAccountNumber]					NVARCHAR (100) NULL,
	[Out_AccountName]								NVARCHAR (100) NULL,
	[Out_IssueType]									NVARCHAR (100) NULL,
	[Out_ISIN]										NVARCHAR (100) NULL,
	[Out_SecurityDescription]						NVARCHAR (100) NULL,
	[Out_AssetLocation]								NVARCHAR (100) NULL,
	[Out_LocationDescription]						NVARCHAR(100) NULL,
	[Out_IssueTypeDescription]						NVARCHAR(100) NULL,
	[Out_LocationCode]								NVARCHAR(100) NULL,
	[Out_RegistrarCode]								NVARCHAR(100) NULL,
	[Out_MaturityDate]								DATETIME2 NULL,
	[Out_TradedAggregate]							NUMERIC (38,20) NULL,
	[Out_RegistrationCode]							NVARCHAR(100) NULL,
	[Out_RegistrarDescription]						NVARCHAR(100) NULL,
	[Out_SettledAggregate]							NUMERIC (38,20) NULL,
	[Out_SecurityOnLoan]							NUMERIC (38,20) NULL,
	[Out_RegistrationDescription]					NVARCHAR(100) NULL,
	[Out_AvailableBalance]							NUMERIC (38,20) NULL,	
	[Out_SEDOL]										NVARCHAR (100) NULL,	
	[Out_SecurityPrice]								NUMERIC (38,20) NULL,			
	[Out_SecurityCurrency]							NVARCHAR (100) NULL,

	[Out_TradedValue_SecurityCurrency]				NUMERIC (38,20) NULL,
	[Out_SettledAggregateValue_SecurityCurrency]	NUMERIC (38,20) NULL,
	[Out_AccountCurrency]							NVARCHAR (100) NULL,
	[Out_TradedValue_AccountCurrency]				NUMERIC (38,20) NULL,
	[Out_SettledAggregateValue_AccountCurrency]		NUMERIC (38,20) NULL,
	[Out_ExchangeRate]								NUMERIC (38,20) NULL,
	
	[Out_HKeyLinkCustodianPosition]					BINARY(20) NULL,	
	[Out_CustodianPositionPL]						NVARCHAR(4000) NULL,	
	[Out_HDiffCustodianPositionPL]					BINARY(20) NULL,	

	[Out_HKeyHubCustodianAccount]					BINARY(20) NULL,	
	[Out_CustodianAccountPL]						NVARCHAR(4000) NULL,
	[Out_HDiffCustodianAccountPL]					BINARY(20) NULL,	
	
	[Out_HKeyHubCustodianSecurity]					BINARY(20) NULL,	
	[Out_CustodianSecurityPL]						NVARCHAR(4000) NULL,
	[Out_HDiffCustodianSecurityPL]					BINARY(20) NULL,	
		
	[Out_HKeyHubSecurityCurrency]					BINARY(20) NULL,

	[Meta_ETLProcessID]								INT	NULL,		
	[Meta_RecordSource]								NVARCHAR (1000) NULL,
	[Meta_LoadDateTime]								DATETIME2 NULL DEFAULT N'9999-12-31',
	[Meta_SrcSysExportDateTime]						DATETIME2 NULL, 	
	[Meta_EffectFromDateTime]						DATETIME2 NULL,
	[Meta_EffectToDateTime]							DATETIME2 NULL,	
	[Meta_ActiveRow]								BIT NULL DEFAULT 1		-- Identify active record e.g. usually last import
)

