CREATE TABLE [stg].[MANUAL_Calendar]
(
	[ID]						INT IDENTITY(1,1) NOT NULL PRIMARY KEY,	

	[In_DateKey]				VARCHAR (100) NULL,
	[In_CalendarDate]			VARCHAR (100) NULL,
	[In_Day]					VARCHAR (100) NULL,
	[In_Month]					VARCHAR (100) NULL,
	[In_Year]					VARCHAR (100) NULL,
	[In_Quarter]				VARCHAR (100) NULL,
	[In_DayOfWeek]				VARCHAR (100) NULL,
	[In_DayOccInMonth]			VARCHAR (100) NULL,
	[In_DayOfQuarter]			VARCHAR (100) NULL,
	[In_DayOfYear]				VARCHAR (100) NULL,
	[In_WeekNumISO]				VARCHAR (100) NULL,
	[In_MonthOfQuarter]			VARCHAR (100) NULL,
	[In_StartOfMonth]			VARCHAR (100) NULL,
	[In_EndOfMonth]				VARCHAR (100) NULL,
	[In_StartOfQuarter]			VARCHAR (100) NULL,
	[In_EndOfQuarter]			VARCHAR (100) NULL,
	[In_StartOfCalYear]			VARCHAR (100) NULL,
	[In_EndOfCalYear]			VARCHAR (100) NULL,
	[In_StartOfFinYear]			VARCHAR (100) NULL,
	[In_EndOfFinYear]			VARCHAR (100) NULL,
	[In_d]						VARCHAR (100) NULL,
	[In_dd]						VARCHAR (100) NULL,
	[In_ddd]					VARCHAR (100) NULL,
	[In_dddd]					VARCHAR (100) NULL,
	[In_m]						VARCHAR (100) NULL,
	[In_mm]						VARCHAR (100) NULL,
	[In_mmm]					VARCHAR (100) NULL,
	[In_mmmm]					VARCHAR (100) NULL,
	[In_q]						VARCHAR (100) NULL,
	[In_qqqq]					VARCHAR (100) NULL,
	[In_yy]						VARCHAR (100) NULL,
	[In_yyyy]					VARCHAR (100) NULL,
	[In_FY_m]					VARCHAR (100) NULL,
	[In_FY_mm]					VARCHAR (100) NULL,
	[In_FY_q]					VARCHAR (100) NULL,
	[In_FY_qqqq]				VARCHAR (100) NULL,
	[In_FY_yy]					VARCHAR (100) NULL,
	[In_FY_yyyy]				VARCHAR (100) NULL,
	[In_IsWeekday]				VARCHAR (100) NULL,
	[In_IsHolidayUK]			VARCHAR (100) NULL,
	[In_HolidayUK]				VARCHAR (100) NULL,

	[Out_DateKey]				INT NULL,
	[Out_CalendarDate]			DATETIME2 NULL,
	[Out_Day]					INT NULL,
	[Out_Month]					INT NULL,
	[Out_Year]					INT NULL,
	[Out_Quarter]				INT NULL,
	[Out_DayOfWeek]				INT NULL,
	[Out_DayOccInMonth]			INT NULL,
	[Out_DayOfQuarter]			INT NULL,
	[Out_DayOfYear]				INT NULL,
	[Out_WeekNumISO]			INT NULL,
	[Out_MonthOfQuarter]		INT NULL,
	[Out_StartOfMonth]			DATETIME2 NULL,
	[Out_EndOfMonth]			DATETIME2 NULL,
	[Out_StartOfQuarter]		DATETIME2 NULL,
	[Out_EndOfQuarter]			DATETIME2 NULL,
	[Out_StartOfCalYear]		DATETIME2 NULL,
	[Out_EndOfCalYear]			DATETIME2 NULL,
	[Out_StartOfFinYear]		DATETIME2 NULL,
	[Out_EndOfFinYear]			DATETIME2 NULL,
	[Out_d]						NVARCHAR(2) NULL,
	[Out_dd]					NCHAR(2) NULL,
	[Out_ddd]					NCHAR(3) NULL,
	[Out_dddd]					NVARCHAR(9) NULL,
	[Out_m]						NVARCHAR(2) NULL,
	[Out_mm]					NCHAR(2) NULL,
	[Out_mmm]					NCHAR(3) NULL,
	[Out_mmmm]					NVARCHAR(9) NULL,
	[Out_q]						NCHAR(1) NULL,
	[Out_qqqq]					NVARCHAR(6) NULL,
	[Out_yy]					NCHAR(2) NULL,
	[Out_yyyy]					NCHAR(4) NULL,
	[Out_FY_m]					NVARCHAR(2) NULL,
	[Out_FY_mm]					NCHAR(2) NULL,
	[Out_FY_q]					NCHAR(1) NULL,
	[Out_FY_qqqq]				NVARCHAR(6) NULL,
	[Out_FY_yy]					NCHAR(2) NULL,
	[Out_FY_yyyy]				NCHAR(4) NULL,
	[Out_IsWeekDay]				BIT NULL,
	[Out_IsHolidayUK]			BIT NULL,
	[Out_HolidayUK]				NVARCHAR(100) NULL,
	
	--[Out_HKeyHubCurrencies]			BINARY(20) NULL,	
	--[Out_CurrencyPL]				NVARCHAR(4000) NULL,	
	--[Out_HDiffCurrencyPL]			BINARY(20) NULL,	
	
	[Meta_ETLProcessID]				INT	NULL,		
	[Meta_RecordSource]				NVARCHAR (1000) NULL,
	[Meta_LoadDateTime]				DATETIME2 NULL DEFAULT N'9999-12-31',
	[Meta_SourceSysExportDateTime]	DATETIME2 NULL, 	
	[Meta_EffectFromDateTime]		DATETIME2 NULL,
	[Meta_EffectToDateTime]			DATETIME2 NULL,	
	[Meta_ActiveRow]				BIT NULL DEFAULT 1		-- Identify active record e.g. usually last import
)

